---
# Rsyslog

- name: "rsyslog | install"
  apt: pkg=rsyslog state=present update_cache=yes

- name: "rsyslog | config"
  template: src="rsyslog.conf.j2" dest="/etc/rsyslog.conf" owner="root" group="root" mode="0644" backup="yes"
  notify: Restart rsyslog

#- name: "rsyslog | restart service"
#  service: name=rsyslog state=restarted
