---
- name: db | create a database
  mysql_db: login_user="{{db.admin_user}}" login_password="{{ db.admin_password }}" name={{ app1.db.name }} collation=utf8_general_ci encoding=utf8 state=present

- name: db | create a database user
  mysql_user: login_user="{{db.admin_user}}" login_password="{{ db.admin_password }}" name={{ app1.db.user }} password="{{ app1.db.user_password }}" priv="{{ app1.db.name }}.*:ALL" host='%' state=present

