---
- name: app1-tests | configure
  template: src="app1-tests.properties.j2" dest="{{ app1.clonedir }}/app1/tests/app1-tests.properties"

- name: app1-tests | wait 20 s
  pause: seconds="20"

- name: app1-tests | run
  shell: mvn verify -Prun-tests
  args:
    chdir: "{{ app1.clonedir }}/app1/tests"

