---
# Clone app
- name: application | delete clonedir
  command: rm -fr {{ app1.clonedir }}/app1
  ignore_errors: yes

- name: application | clone
  git: repo="{{ app1.repo }}" dest="{{ app1.clonedir }}/app1"
  ignore_errors: yes

- name: application | package
  command: mvn clean package -f {{ app1.clonedir }}/app1/pom.xml

- name: db-upgrader | configure
  template: src="db-upgrader.properties.j2" dest="{{ app1.clonedir }}/app1/db-upgrader/app1-db-upgrader.properties"

- name: db-upgrader | run
  command: java -jar {{ app1.clonedir }}/app1/db-upgrader/target/app1-db-upgrader.jar --spring.config.location={{ app1.clonedir }}/app1/db-upgrader/ --spring.config.name=app1-db-upgrader

- name: index-upgrader | configure
  template: src="index-upgrader.properties.j2" dest="{{ app1.clonedir }}/app1/index-upgrader/app1-index-upgrader.properties"

- name: index-upgrader | run
  command: java -jar {{ app1.clonedir }}/app1/index-upgrader/target/app1-index-upgrader.jar --spring.config.location={{ app1.clonedir }}/app1/index-upgrader/ --spring.config.name=app1-index-upgrader

- name: application | configure
  template: src=app1-api.yml.j2 dest="{{ app1.clonedir }}/app1/api/app1-api.yml"

- name: logback | configure
  template: src="logback.xml.j2" dest="{{ app1.clonedir }}/app1/api/logback.xml"

